#!/bin/bash

# dependencies ─────────────────────────────────────────────────────────────────

script="$(basename -- ${BASH_SOURCE[0]})"

if [[ "${frobulator_loaded}" != "true" ]]
then
	echo

	ticker () {

		for ticker in '>  ' '>> ' '>>>'
		do
			echo -n -e "\r[  ${ticker}  ] ${1^}..."

			sleep 0.5
		done

		echo

		echo

	}

	if [[ $(id -u -n) = "root" ]]
	then
		USER="${SUDO_USER:-root}"

		if [ "${USER}" = "root" ]
		then
			HOME=/root
		else
			HOME="/home/${USER}"
		fi
	fi

	ticker checking

	package_managers_list=(
		"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
		"dnf --quiet install --assumeyes"
		"yum --quiet install --assumeyes"
		"apk add --quiet"
		"pacman --sync --refresh --noconfirm --noprogressbar"
		"zypper --quiet --non-interactive install"
	)

	package="curl"

	if [[ -z $(command -v "${package}") ]]
	then
		for package_manager in "${package_managers_list[@]}"
		do
			entry="${package_manager%% *}"

			if [[ -n $(command -v "${entry}") ]]
			then
				eval "${package_manager} ${package} > /dev/null 2>&1"

				break
			fi
		done

		if [[ -z $(command -v "${package}") ]]
		then
			echo "[  !  ] Unable to install or binary not found ─────────────────────── [ '${package}' ]"
			echo

			exit 1
		fi
	fi

	mkdir -p "${HOME}"/.local/bin

	frobulator="${HOME}"/.local/bin/frobulator

	version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^update=' | cut -d '"' -f 2)

	version_local=$(grep -m 1 '^update=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)

	version_local="${version_local:-1970-01-01}"

	if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
	then
		curl -s -L get.frbltr.app > "${frobulator}"

		chmod +x "${frobulator}"
	fi

	ticker initializing

	source "${frobulator}"

	# script arguments for escalation

	self_arguments=("${@}")
fi

# superuser ────────────────────────────────────────────────────────────────────

frobulator.escalate

# script ───────────────────────────────────────────────────────────────────────

frobulator.script

# version ──────────────────────────────────────────────────────────────────────

version="2026-09-29"

# usage ────────────────────────────────────────────────────────────────────────

while (($#))
do
	case "${1}"
	in
		-d|--directory)
			directory="${2}"

			shift
		;;

		-a|--all)
			option="all"
		;;

		-e|--export)
			option="exports"
		;;

		-r|--render)
			option="renders"
		;;

		-s|--instructions)
			option="instructions"
		;;

		-m|--models)
			option="models"
		;;

		-i|--images)
			option="images"
		;;

		-w|--drawer)
			option="drawer"
		;;

		-u|--menu)
			option="menu"
		;;

		-v|--viewer)
			option="viewer"
		;;

		-x|--index)
			option="index"
		;;

		-h|--help)
			echo
			echo -e "Usage: ./${script} [DIRECTORY] | [OPTION] [PARAMETER]"
			echo
			echo -e "Options:"
			echo
			echo -e "-d, --directory       Specify [d]irectory to load models from."
			echo
			echo -e "-a, --all             Update [a]ll website framework and content."
			echo
			echo -e "-e, --export          Update models [e]xports content."
			echo
			echo -e "-r, --render          Update models [r]enders content."
			echo
			echo -e "-s, --instructions    Update models in[s]tructions content."
			echo
			echo -e "-m, --models          Update [m]odels content."
			echo
			echo -e "-i, --images          Update model [i]mages."
			echo
			echo -e "-w, --drawer          Update dra[w]er content."
			echo
			echo -e "-u, --menu            Update models men[u] content."
			echo
			echo -e "-v, --viewer          Update models [v]iewer content."
			echo
			echo -e "-x, --index           Update website inde[x]ing sitemap."
			echo
			echo -e "-h, --help            Show [h]elp and usage information."
			echo
			echo -e "'${script}'           [ Version // ${version} ]"
			echo

			exit
		;;

		"")
			# handle empty argument:
			# use default values specified in script

			:
		;;

		*)
			echo
			echo -e "Usage: ./${script} [DIRECTORY] | [OPTION] [PARAMETER]"
			echo
			echo -e "Unknown option: '${script} ${1}':"
			echo -e "Type './${script} -h' for help and usage information."
			echo

			exit 1

		;;

		esac

	shift

done

# clear ────────────────────────────────────────────────────────────────────────

frobulator.clear

# variables ────────────────────────────────────────────────────────────────────

export directory="${directory}"

# defaults ─────────────────────────────────────────────────────────────────────

# functions ────────────────────────────────────────────────────────────────────

upload () {

	message="${1}"

	git add *

	git commit		\
		--all		\
		--message="${message}"

	git push > "${sink}" 2>&1

	echo
}

option () {

	for script in ${list[@]}
	do
		"${SHELL}" "${PWD}"/"${script}"
	done

	upload "Models update" &

	frobulator.fwd "Updating..."

	list=()
}

# requirements ─────────────────────────────────────────────────────────────────

list+=(
	git
	rsync
)

frobulator.assess ${list[@]}

list=()

# update ───────────────────────────────────────────────────────────────────────

if [[ "${option}" = "all" ]]
then
	list+=(
		mechablocks-exports
		mechablocks-renders
		mechablocks-instructions
		mechablocks-models
		mechablocks-images
		mechablocks-drawer
#		mechablocks-menu
		mechablocks-viewer
		mechablocks-index
	)
fi

if [[ "${option}" = "exports" ]]
then
	list+=(
		mechablocks-exports
	)
fi

if [[ "${option}" = "renders" ]]
then
	list+=(
		mechablocks-renders
	)
fi

if [[ "${option}" = "instructions" ]]
then
	list+=(
		mechablocks-instructions
	)
fi

if [[ "${option}" = "models" ]]
then
	list+=(
		mechablocks-models
	)
fi

if [[ "${option}" = "images" ]]
then
	list+=(
		mechablocks-images
	)
fi

if [[ "${option}" = "drawer" ]]
then
	list+=(
		mechablocks-drawer
	)
fi

if [[ "${option}" = "menu" ]]
then
	list+=(
		mechablocks-menu
	)
fi

if [[ "${option}" = "viewer" ]]
then
	list+=(
		mechablocks-viewer
	)
fi

if [[ "${option}" = "index" ]]
then
	list+=(
		mechablocks-index
	)
fi

option ${list[@]}

list=()

frobulator.scs "Done" "[ Update ]"
